// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9pw2mOfw30Iq9WeywPKBDmN0wfmTUXsw',
    appId: '1:885468302296:web:4a5a595e4dc90f00a080ad',
    messagingSenderId: '885468302296',
    projectId: 'fooddeliveryapp-1241a',
    authDomain: 'fooddeliveryapp-1241a.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-1241a.firebasestorage.app',
    measurementId: 'G-XVVT0RNMDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZO_PY6aORpWFRAdLAdl9omgVjNYTTlvU',
    appId: '1:885468302296:android:c345f85c4425fd9ea080ad',
    messagingSenderId: '885468302296',
    projectId: 'fooddeliveryapp-1241a',
    storageBucket: 'fooddeliveryapp-1241a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa_neJAmgETn2EVKOXJPb18v2CzaKGeOk',
    appId: '1:885468302296:ios:9a4b84253ed0c9bfa080ad',
    messagingSenderId: '885468302296',
    projectId: 'fooddeliveryapp-1241a',
    storageBucket: 'fooddeliveryapp-1241a.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa_neJAmgETn2EVKOXJPb18v2CzaKGeOk',
    appId: '1:885468302296:ios:9a4b84253ed0c9bfa080ad',
    messagingSenderId: '885468302296',
    projectId: 'fooddeliveryapp-1241a',
    storageBucket: 'fooddeliveryapp-1241a.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9pw2mOfw30Iq9WeywPKBDmN0wfmTUXsw',
    appId: '1:885468302296:web:4e8eae2977d3cdeba080ad',
    messagingSenderId: '885468302296',
    projectId: 'fooddeliveryapp-1241a',
    authDomain: 'fooddeliveryapp-1241a.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-1241a.firebasestorage.app',
    measurementId: 'G-W3R882S3L7',
  );
}
